export const internshipStats = [
  {
    title: "Total Revenue Generated",
    value: "$142.6K",
    change: "+22%",
    subtitle: "vs last quarter",
    color: "emerald",
  },
  {
    title: "Completion Rate",
    value: "92%",
    change: "",
    subtitle: "Program success rate",
    color: "blue",
  },
  {
    title: "Placement Rate",
    value: "78%",
    change: "",
    subtitle: "Post-internship hiring",
    color: "purple",
  },
];

export const internsData = [
  {
    id: 1,
    name: "John Anderson",
    email: "john.a@email.com",
    program: "Software Engineering",
    department: "Engineering",
    duration: "6 months",
    mentor: "Alex Thompson",
    progress: 85,
    placement: "Shortlisted",
    status: "Active",
  },
  {
    id: 2,
    name: "Lisa Martinez",
    email: "lisa.m@email.com",
    program: "UI/UX Design",
    department: "Design",
    duration: "3 months",
    mentor: "Maria Garcia",
    progress: 60,
    placement: "Under Review",
    status: "Active",
  },
  {
    id: 3,
    name: "Kevin Park",
    email: "kevin.p@email.com",
    program: "Data Analytics",
    department: "Analytics",
    duration: "6 months",
    mentor: "David Kim",
    progress: 75,
    placement: "Shortlisted",
    status: "Active",
  },
  {
    id: 4,
    name: "Sophie Williams",
    email: "sophie.w@email.com",
    program: "Product Management",
    department: "Product",
    duration: "4 months",
    mentor: "Sarah Johnson",
    progress: 45,
    placement: "Pending",
    status: "Active",
  },
  {
    id: 5,
    name: "Marcus Thompson",
    email: "marcus.t@email.com",
    program: "Cloud Engineering",
    department: "Infrastructure",
    duration: "6 months",
    mentor: "James Wilson",
    progress: 30,
    placement: "N/A",
    status: "Dropped Out",
  },
  {
    id: 6,
    name: "Priya Patel",
    email: "priya.p@email.com",
    program: "Digital Marketing",
    department: "Marketing",
    duration: "3 months",
    mentor: "Emily Chen",
    progress: 100,
    placement: "Placed",
    status: "Completed",
  },
];