export const internshipStats = [
  {
    title: "Total Revenue Generated",
    value: "$142.6K",
    change: "+22%",
    subtitle: "vs last quarter",
    color: "emerald",
  },
  {
    title: "Completion Rate",
    value: "92%",
    change: "",
    subtitle: "Program success rate",
    color: "blue",
  },
  {
    title: "Placement Rate",
    value: "78%",
    change: "",
    subtitle: "Post-internship hiring",
    color: "purple",
  },
];

export const internsData = [
  {
    id: 1,
    name: "John Anderson",
    email: "john.a@email.com",
    phone: "+1 (555) 234-5678",
    program: "Software Engineering",
    department: "Engineering",
    duration: "6 months",
    startDate: "Jan 15, 2026",
    endDate: "Jul 15, 2026",
    mentor: "Alex Thompson",
    salesAgent: "Rachel Green",
    education: "Bachelor's in Computer Science",
    university: "MIT",
    progress: 85,
    projectsCompleted: "3/4",
    placement: "Shortlisted",
    status: "Active",
    courseCost: "$4,500",
    skills: ["React", "Node.js", "PostgreSQL", "Docker"],
  },
  {
    id: 2,
    name: "Lisa Martinez",
    email: "lisa.m@email.com",
    phone: "+1 (555) 345-6789",
    program: "UI/UX Design",
    department: "Design",
    duration: "3 months",
    startDate: "Feb 1, 2026",
    endDate: "May 1, 2026",
    mentor: "Maria Garcia",
    salesAgent: "Rachel Green",
    education: "Bachelor's in Design",
    university: "Stanford University",
    progress: 60,
    projectsCompleted: "2/4",
    placement: "Under Review",
    status: "Active",
    courseCost: "$3,200",
    skills: ["Figma", "Wireframing", "User Research", "Prototyping"],
  },
  {
    id: 3,
    name: "Kevin Park",
    email: "kevin.p@email.com",
    phone: "+1 (555) 456-7890",
    program: "Data Analytics",
    department: "Analytics",
    duration: "6 months",
    startDate: "Jan 20, 2026",
    endDate: "Jul 20, 2026",
    mentor: "David Kim",
    salesAgent: "Monica Geller",
    education: "Bachelor's in Statistics",
    university: "Harvard University",
    progress: 75,
    projectsCompleted: "3/5",
    placement: "Shortlisted",
    status: "Active",
    courseCost: "$4,000",
    skills: ["Python", "SQL", "Power BI", "Excel"],
  },
  {
    id: 4,
    name: "Sophie Williams",
    email: "sophie.w@email.com",
    phone: "+1 (555) 567-8901",
    program: "Product Management",
    department: "Product",
    duration: "4 months",
    startDate: "Mar 1, 2026",
    endDate: "Jul 1, 2026",
    mentor: "Sarah Johnson",
    salesAgent: "Rachel Green",
    education: "Bachelor's in Business Administration",
    university: "University of California",
    progress: 45,
    projectsCompleted: "1/4",
    placement: "Pending",
    status: "Active",
    courseCost: "$3,800",
    skills: ["Product Strategy", "Agile", "Market Research", "Roadmapping"],
  },
  {
    id: 5,
    name: "Marcus Thompson",
    email: "marcus.t@email.com",
    phone: "+1 (555) 678-9012",
    program: "Cloud Engineering",
    department: "Infrastructure",
    duration: "6 months",
    startDate: "Jan 10, 2026",
    endDate: "Jul 10, 2026",
    mentor: "James Wilson",
    salesAgent: "Monica Geller",
    education: "Bachelor's in Information Technology",
    university: "Georgia Tech",
    progress: 30,
    projectsCompleted: "1/4",
    placement: "N/A",
    status: "Dropped Out",
    courseCost: "$4,800",
    skills: ["AWS", "Docker", "Linux", "Networking"],
  },
  {
    id: 6,
    name: "Priya Patel",
    email: "priya.p@email.com",
    phone: "+1 (555) 789-0123",
    program: "Digital Marketing",
    department: "Marketing",
    duration: "3 months",
    startDate: "Feb 15, 2026",
    endDate: "May 15, 2026",
    mentor: "Emily Chen",
    salesAgent: "Rachel Green",
    education: "Bachelor's in Marketing",
    university: "New York University",
    progress: 100,
    projectsCompleted: "4/4",
    placement: "Placed",
    status: "Completed",
    courseCost: "$2,900",
    skills: ["SEO", "Google Ads", "Content Strategy", "Analytics"],
  },
];