// src/components/sales/ProjectsTable.jsx

"use client";

import { useState, useEffect } from "react";
import { api } from "@/lib/api";
import BudgetModal from "./BudgetModal";
import StatusBadge from "./StatusBadge";

import {
  Eye,
  Download,
  MoreVertical,
} from "lucide-react";

export default function ProjectsTable({ onViewProject }) {
  const [dbProjects, setDbProjects] = useState([]);
  const [selectedProject, setSelectedProject] = useState(null);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    api
      .get("/api/projects")
      .then((res) => setDbProjects(res.data || []))
      .catch((err) => console.error("Failed DB projects fetch:", err));
  }, []);

  const combinedProjects = dbProjects;

  const handleDownloadReport = () => {
    const reportWindow = window.open("", "_blank", "width=1600,height=900");

    const rows = combinedProjects
    .map(
      (project) => `
        <tr>
          <td>${project.project}</td>
          <td>${project.client}</td>
          <td>${project.agreed}</td>
          <td>${project.received}</td>
          <td>${project.remaining}</td>
          <td>${project.deadline}</td>
          <td>${project.manager}</td>
          <td>${project.status}</td>
        </tr>
      `
    )
    .join("");

  reportWindow.document.write(`
    <html>
      <head>
        <title>Client Projects Financial Report</title>
        <style>
          @page {
            size: A4 landscape;
            margin: 0;
          }

          * {
            box-sizing: border-box;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }

          body {
            margin: 0;
            background: white;
            font-family: Arial, sans-serif;
            color: #020617;
          }

          .page {
            width: 100%;
            padding: 50px 36px;
          }

          h1 {
            font-size: 28px;
            margin: 0 0 16px;
            color: #07152f;
          }

          .meta {
            font-size: 14px;
            margin-bottom: 28px;
            color: #334155;
          }

          .cards {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 24px;
            margin-bottom: 28px;
          }

          .card {
            background: #f3f7fd;
            border-radius: 8px;
            padding: 18px 24px;
          }

          .card strong {
            display: block;
            font-size: 26px;
            color: #123b68;
          }

          .card span {
            font-size: 14px;
            color: #334155;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
          }

          th {
            background: #213f66;
            color: white;
            text-align: left;
            padding: 12px 14px;
            font-weight: 700;
          }

          td {
            padding: 11px 14px;
            border-bottom: 1px solid #dbe3ef;
            color: #020617;
          }

          tbody tr:nth-child(even) {
            background: #f3f7fd;
          }

          .footer {
            margin-top: 36px;
            font-size: 13px;
            color: #64748b;
          }
        </style>
      </head>

      <body>
        <div class="page">
          <h1>Client Projects Financial Report</h1>
          <div class="meta">Generated: June 24, 2026 &nbsp; | &nbsp; Period: June 2026</div>

          <div class="cards">
            <div class="card"><strong>24</strong><span>Total Projects</span></div>
            <div class="card"><strong>$2.85M</strong><span>Total Revenue</span></div>
            <div class="card"><strong>$385K</strong><span>June Revenue</span></div>
          </div>

          <table>
            <thead>
              <tr>
                <th>Project</th>
                <th>Client</th>
                <th>Budget</th>
                <th>Received</th>
                <th>Pending</th>
                <th>Due Date</th>
                <th>Manager</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>

          <div class="footer">
            Auto-generated by Sales Dashboard. Confidential – Internal Use Only.
          </div>
        </div>

        <script>
          window.onload = () => window.print();
        </script>
      </body>
    </html>
  `);

  reportWindow.document.close();
};


const handleDownloadInvoice = (project) => {
  const today = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  const fileName = `Invoice_${project.project.replace(/[^a-z0-9]/gi, "_")}.html`;

  const paymentRows = project.payments
    .map(
      (payment) => `
        <tr>
          <td>${payment.date}</td>
          <td>${payment.amount}</td>
          <td>${payment.title}</td>
        </tr>
      `
    )
    .join("");

  const invoiceHTML = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Invoice - ${project.project}</title>

        <style>
          body {
            margin: 0;
            background: #ffffff;
            color: #0f172a;
            font-family: Arial, Helvetica, sans-serif;
          }

          .invoice {
            width: 760px;
            margin: 70px auto;
          }

          h1 {
            margin: 0 0 22px;
            font-size: 30px;
            letter-spacing: 1px;
            color: #17375e;
          }

          .meta {
            font-size: 14px;
            color: #475569;
            margin-bottom: 36px;
          }

          .meta strong {
            color: #334155;
          }

          .details {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 24px;
            font-size: 16px;
          }

          .details td {
            padding: 10px 0;
            border-bottom: 1px solid #e2e8f0;
          }

          .details td:first-child {
            font-weight: 500;
            width: 36%;
          }

          .details td:last-child {
            text-align: right;
          }

          .bold {
            font-weight: 700;
          }

          .green {
            color: #059669;
            font-weight: 700;
          }

          .red {
            color: #991b1b;
            font-weight: 700;
          }

          .payments {
            width: 100%;
            border-collapse: collapse;
            margin-top: 22px;
            font-size: 16px;
          }

          .payments th {
            background: #1f426e;
            color: #ffffff;
            text-align: left;
            padding: 12px 14px;
          }

          .payments td {
            padding: 11px 14px;
            border-bottom: 1px solid #e2e8f0;
          }

          .footer {
            margin-top: 34px;
            font-size: 12px;
            color: #64748b;
          }
        </style>
      </head>

      <body>
        <div class="invoice">
          <h1>INVOICE</h1>

          <div class="meta">
            Project: <strong>${project.project}</strong>
            &nbsp;|&nbsp;
            Client: <strong>${project.client}</strong>
          </div>

          <table class="details">
            <tr>
              <td>Lead Manager</td>
              <td>${project.manager}</td>
            </tr>

            <tr>
              <td>Deadline</td>
              <td>${project.deadline}</td>
            </tr>

            <tr>
              <td>Payment Due Date</td>
              <td>${project.deadline}</td>
            </tr>

            <tr>
              <td>Services</td>
              <td>${project.services.join(", ")}</td>
            </tr>

            <tr>
              <td class="bold">Total Agreed Amount</td>
              <td class="bold">${project.agreed}</td>
            </tr>

            <tr>
              <td class="bold">Total Received</td>
              <td class="green">${project.received}</td>
            </tr>

            <tr>
              <td class="bold">Remaining Balance</td>
              <td class="red">${project.remaining}</td>
            </tr>
          </table>

          <table class="payments">
            <thead>
              <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Note</th>
              </tr>
            </thead>

            <tbody>
              ${paymentRows}
            </tbody>
          </table>

          <div class="footer">
            Generated ${today} — Confidential
          </div>
        </div>
      </body>
    </html>
  `;

  const blob = new Blob([invoiceHTML], {
    type: "text/html",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  link.click();

  URL.revokeObjectURL(url);
};

  return (
    <div className="glass-card rounded-2xl p-6 border border-border">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold text-foreground">
            Client Projects Detailed View
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Manage and track all client projects. Click Budget for Financial Overview
          </p>
        </div>

        <button
  onClick={handleDownloadReport}
  className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition"
>
  View Reports
</button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[1300px] text-left border-collapse">
          <thead>
            <tr className="border-b border-border text-xs uppercase text-muted-foreground tracking-wider">
              <th className="py-4 px-4 whitespace-nowrap font-bold">Project Name</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Client Name</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Budget</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Lead Manager</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Deadline</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Progress</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Status</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Report</th>
              <th className="py-4 px-4 whitespace-nowrap font-bold">Actions</th>
            </tr>
          </thead>

          <tbody className="divide-y divide-border/40 text-sm">
            {combinedProjects.map((project) => (
              <tr
                key={project.id || project._id}
                className="hover:bg-muted/30 transition-colors"
              >
                <td className="py-4 px-4 font-bold text-foreground whitespace-nowrap">
                  {project.project}
                </td>

                <td className="py-4 px-4 text-muted-foreground whitespace-nowrap">
                  {project.client}
                </td>

                <td className="py-4 px-4 whitespace-nowrap">
                  <button
                    onClick={() => {
                      setSelectedProject(project);
                      setOpen(true);
                    }}
                    className="font-bold underline text-emerald-400 hover:text-emerald-300 transition"
                  >
                    {project.budget}
                  </button>
                </td>

                <td className="py-4 px-4 font-medium text-foreground whitespace-nowrap">
                  {project.manager}
                </td>

                <td className="py-4 px-4 text-muted-foreground whitespace-nowrap">
                  {project.deadline}
                </td>

                <td className="py-4 px-4 w-[220px] min-w-[180px]">
                  <div className="flex items-center gap-3">
                    <div className="w-32 h-2.5 bg-zinc-800 rounded-full overflow-hidden border border-border/50">
                      <div
                        className="h-full bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 rounded-full transition-all duration-500 shadow-sm shadow-indigo-500/30"
                        style={{
                          width: `${project.progress}%`,
                        }}
                      />
                    </div>

                    <span className="text-sm font-bold text-indigo-400">
                      {project.progress}%
                    </span>
                  </div>
                </td>

                <td className="py-4 px-4 whitespace-nowrap">
                  <StatusBadge status={project.status} />
                </td>

                <td className="py-4 px-4 whitespace-nowrap">
                  <button
                    onClick={() => onViewProject(project)}
                    className="flex items-center gap-2 px-3.5 py-2 rounded-xl border border-border/80 hover:bg-indigo-500/10 hover:border-indigo-500/40 text-xs font-bold transition shadow-sm"
                  >
                    <Eye size={15} className="text-indigo-400" />
                    View Project
                  </button>
                </td>

                <td className="py-4 px-4 whitespace-nowrap">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleDownloadInvoice(project)}
                      className="p-2 rounded-xl border border-border/80 hover:bg-muted text-muted-foreground hover:text-foreground transition shadow-sm"
                      title="Download Invoice"
                    >
                      <Download size={16} />
                    </button>

                    <button className="p-2 rounded-xl border border-border/80 hover:bg-muted text-muted-foreground hover:text-foreground transition shadow-sm">
                      <MoreVertical size={16} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {selectedProject && (
  <BudgetModal
    project={selectedProject}
    onClose={() => {
      setSelectedProject(null);
      setOpen(false);
    }}
  />
)}

    </div>
  );
}
