import { Target, IndianRupee, TrendingUp } from "lucide-react";

export const employeeInfo = {
  name: "Rahul Sharma",
  initials: "RS",
  role: "Senior Sales Executive",
  id: "EMP001",
  status: "Active",
  month: "June 2026",
};

export const tabs = ["Client Projects", "Internships", "Training"];

export const employeeStats = {
  "Client Projects": [
    {
      title: "Total Active Leads",
      value: "24",
      change: "+12%",
      subtitle: "this month",
      icon: Target,
      color: "rose",
    },
    {
      title: "Revenue Pipeline",
      value: "₹18.4L",
      change: "+8.3%",
      subtitle: "from last month",
      icon: IndianRupee,
      color: "purple",
    },
    {
      title: "Conversion Rate",
      value: "74.8%",
      change: "+5.2%",
      subtitle: "improvement",
      icon: TrendingUp,
      color: "red",
    },
  ],

  Internships: [
  {
    title: "Total Candidates Brought",
    value: "45",
    change: "+18",
    subtitle: "this month",
    icon: Target,
    color: "cyan",
  },
  {
    title: "Total Fee Collected",
    value: "₹1.84L",
    change: "+22%",
    subtitle: "this month",
    icon: IndianRupee,
    color: "blue",
  },
  {
    title: "Placement Rate",
    value: "72%",
    change: "+8%",
    subtitle: "improvement",
    icon: TrendingUp,
    color: "indigo",
  },
],

  Training: [
    {
      title: "Total Trainings Brought",
      value: "12",
      change: "+7%",
      subtitle: "this month",
      icon: Target,
      color: "amber",
    },
    {
      title: "Training Revenue",
      value: "₹9.2L",
      change: "+10.5%",
      subtitle: "from last month",
      icon: IndianRupee,
      color: "orange",
    },
    {
      title: "Completion Rate",
      value: "81.2%",
      change: "+6.8%",
      subtitle: "improvement",
      icon: TrendingUp,
      color: "emerald",
    },
  ],
};

export const monthlyData = {
  "Client Projects": [
    {
      month: "June 2026",
      badge: "Current",
      records: [
        {
          projectName: "E-Commerce Platform",
          clientName: "RetailX Corp",
          budget: "₹4,50,000",
          leadStatus: "On Track",
          approvalStatus: "Approved",
          status: "On Track",
          approval: "Approved",
          deadline: "30 Jun 2026",
          submitted: "02 Jun 2026",
          submittedDate: "02 Jun 2026",
        },
        {
          projectName: "CRM Integration Suite",
          clientName: "Synapse Technologies",
          budget: "₹2,80,000",
          leadStatus: "Pending Approval",
          approvalStatus: "Pending Approval",
          status: "Pending Approval",
          approval: "Pending Approval",
          deadline: "28 Jun 2026",
          submitted: "05 Jun 2026",
          submittedDate: "05 Jun 2026",
        },
        {
          projectName: "Mobile App Development",
          clientName: "UrbanEase Pvt Ltd",
          budget: "₹6,20,000",
          leadStatus: "On Track",
          approvalStatus: "Approved",
          status: "On Track",
          approval: "Approved",
          deadline: "15 Jul 2026",
          submitted: "08 Jun 2026",
          submittedDate: "08 Jun 2026",
        },
        {
          projectName: "Digital Marketing Suite",
          clientName: "BrandBoost Inc",
          budget: "₹1,20,000",
          leadStatus: "Needs Update",
          approvalStatus: "Needs Update",
          status: "Needs Update",
          approval: "Needs Update",
          deadline: "20 Jun 2026",
          submitted: "10 Jun 2026",
          submittedDate: "10 Jun 2026",
        },
      ],
    },
    {
      month: "May 2026",
      badge: "",
      records: [
        {
          projectName: "Cloud Migration",
          clientName: "DataVault Systems",
          budget: "₹5,10,000",
          leadStatus: "On Track",
          approvalStatus: "Approved",
          status: "On Track",
          approval: "Approved",
          deadline: "25 May 2026",
          submitted: "06 May 2026",
          submittedDate: "06 May 2026",
        },
        {
          projectName: "Website Redesign",
          clientName: "GreenLeaf Organics",
          budget: "₹95,000",
          leadStatus: "Rejected",
          approvalStatus: "Rejected",
          status: "Rejected",
          approval: "Rejected",
          deadline: "20 May 2026",
          submitted: "02 May 2026",
          submittedDate: "02 May 2026",
        },
        {
          projectName: "Inventory Management Portal",
          clientName: "SupplyCore Ltd",
          budget: "₹2,80,000",
          leadStatus: "Approved",
          approvalStatus: "Approved",
          status: "Approved",
          approval: "Approved",
          deadline: "29 May 2026",
          submitted: "11 May 2026",
          submittedDate: "11 May 2026",
        },
      ],
    },
    {
      month: "April 2026",
      badge: "",
      records: [
        {
          projectName: "HR Management System",
          clientName: "PeopleFirst Solutions",
          budget: "₹3,40,000",
          leadStatus: "Approved",
          approvalStatus: "Approved",
          status: "Approved",
          approval: "Approved",
          deadline: "18 Apr 2026",
          submitted: "01 Apr 2026",
          submittedDate: "01 Apr 2026",
        },
        {
          projectName: "Booking Portal",
          clientName: "TravelNest India",
          budget: "₹2,10,000",
          leadStatus: "On Track",
          approvalStatus: "Approved",
          status: "On Track",
          approval: "Approved",
          deadline: "22 Apr 2026",
          submitted: "04 Apr 2026",
          submittedDate: "04 Apr 2026",
        },
      ],
    },
  ],

Internships: [
  {
    month: "June 2026",
    badge: "Current",
    records: [
      {
        candidateName: "Neha Gupta",
        program: "Full Stack Development",
        email: "neha.gupta@gmail.com",
        phone: "+91 98765 43210",
        courseFee: "₹25,000",
        duration: "3 Months",
        approvalStatus: "Approved",
        approval: "Approved",
        placement: "Placed",
        submittedDate: "01 Jun 2026",
        submitted: "01 Jun 2026",
      },
      {
        candidateName: "Rohan Verma",
        program: "Digital Marketing",
        email: "rohan.verma@gmail.com",
        phone: "+91 87654 32109",
        courseFee: "₹18,000",
        duration: "2 Months",
        approvalStatus: "Pending Approval",
        approval: "Pending Approval",
        placement: "In Process",
        submittedDate: "03 Jun 2026",
        submitted: "03 Jun 2026",
      },
      {
        candidateName: "Simran Kaur",
        program: "Data Science & ML",
        email: "simran.kaur@gmail.com",
        phone: "+91 76543 21098",
        courseFee: "₹30,000",
        duration: "6 Months",
        approvalStatus: "Approved",
        approval: "Approved",
        placement: "Interview Scheduled",
        submittedDate: "06 Jun 2026",
        submitted: "06 Jun 2026",
      },
    ],
  },
  {
    month: "May 2026",
    badge: "",
    records: [
      {
        candidateName: "Aman Verma",
        program: "Cloud Computing",
        email: "aman.verma@gmail.com",
        phone: "+91 98765 12340",
        courseFee: "₹28,000",
        duration: "3 Months",
        approvalStatus: "Approved",
        approval: "Approved",
        placement: "Placed",
        submittedDate: "12 May 2026",
        submitted: "12 May 2026",
      },
      {
        candidateName: "Priya Singh",
        program: "UI/UX Design",
        email: "priya.singh@gmail.com",
        phone: "+91 99887 77665",
        courseFee: "₹22,000",
        duration: "2 Months",
        approvalStatus: "Needs Update",
        approval: "Needs Update",
        placement: "Not Placed",
        submittedDate: "18 May 2026",
        submitted: "18 May 2026",
      },
    ],
  },
  {
    month: "April 2026",
    badge: "",
    records: [
      {
        candidateName: "Karan Malhotra",
        program: "Cyber Security",
        email: "karan.malhotra@gmail.com",
        phone: "+91 90909 80808",
        courseFee: "₹35,000",
        duration: "4 Months",
        approvalStatus: "Approved",
        approval: "Approved",
        placement: "Placed",
        submittedDate: "08 Apr 2026",
        submitted: "08 Apr 2026",
      },
    ],
  },
],

  Training: [
    {
      month: "June 2026",
      badge: "Current",
      records: [
        {
          trainingProgram: "Corporate Sales Training",
          trainingName: "Corporate Sales Training",
          clientName: "BrightEdge Corp",
          trainingFee: "₹1,20,000",
          fee: "₹1,20,000",
          status: "Approved",
          approvalStatus: "Approved",
          approval: "Approved",
          startDate: "18 Jun 2026",
          submittedDate: "07 Jun 2026",
          submitted: "07 Jun 2026",
        },
        {
          trainingProgram: "React Developer Training",
          trainingName: "React Developer Training",
          clientName: "TechBridge Academy",
          trainingFee: "₹90,000",
          fee: "₹90,000",
          status: "Pending Approval",
          approvalStatus: "Pending Approval",
          approval: "Pending Approval",
          startDate: "24 Jun 2026",
          submittedDate: "10 Jun 2026",
          submitted: "10 Jun 2026",
        },
        {
          trainingProgram: "Advanced Excel Training",
          trainingName: "Advanced Excel Training",
          clientName: "FinEdge Consultants",
          trainingFee: "₹75,000",
          fee: "₹75,000",
          status: "On Track",
          approvalStatus: "Approved",
          approval: "Approved",
          startDate: "27 Jun 2026",
          submittedDate: "12 Jun 2026",
          submitted: "12 Jun 2026",
        },
      ],
    },
    {
      month: "May 2026",
      badge: "",
      records: [
        {
          trainingProgram: "AWS Basics Training",
          trainingName: "AWS Basics Training",
          clientName: "CloudPeak Pvt Ltd",
          trainingFee: "₹1,50,000",
          fee: "₹1,50,000",
          status: "Approved",
          approvalStatus: "Approved",
          approval: "Approved",
          startDate: "15 May 2026",
          submittedDate: "02 May 2026",
          submitted: "02 May 2026",
        },
        {
          trainingProgram: "Digital Marketing Bootcamp",
          trainingName: "Digital Marketing Bootcamp",
          clientName: "MarketMinds Academy",
          trainingFee: "₹1,10,000",
          fee: "₹1,10,000",
          status: "Needs Update",
          approvalStatus: "Needs Update",
          approval: "Needs Update",
          startDate: "21 May 2026",
          submittedDate: "06 May 2026",
          submitted: "06 May 2026",
        },
      ],
    },
  ],
};