export const trainingStats = [
  {
    id: 1,
    title: "Revenue Through Training",
    value: "$168.5K",
    subText: "+15% YoY",
    icon: "revenue",
  },
  {
    id: 2,
    title: "Total Programs",
    value: "15",
    subText: "Programs",
    icon: "book",
  },
  {
    id: 3,
    title: "Total Enrolled",
    value: "124",
    subText: "Students",
    icon: "users",
  },
  {
    id: 4,
    title: "Completion Rate",
    value: "87%",
    subText: "Average",
    icon: "trend",
  },
  {
    id: 5,
    title: "Certifications Issued",
    value: "156",
    subText: "YTD",
    icon: "award",
  },
];

export const enrollmentData = [
  { month: "Jan", enrollments: 45 },
  { month: "Feb", enrollments: 52 },
  { month: "Mar", enrollments: 48 },
  { month: "Apr", enrollments: 61 },
  { month: "May", enrollments: 55 },
  { month: "Jun", enrollments: 68 },
];

export const trainingPrograms = [
  {
    id: 1,
    name: "Advanced React Development",
    category: "Technical",
    duration: "8 weeks",
    instructor: "Alex Thompson",
    enrolled: 24,
    completed: 18,
    revenue: "$48K",
    progress: 75,
    status: "Active",
    participants: [
      {
        id: 1,
        name: "Emma Wilson",
        email: "emma.w@email.com",
        contact: "+1 (555) 111-2222",
        progress: 90,
        status: "Enrolled",
        attendance: 95,
        startDate: "Jan 10, 2026",
        course: "Advanced React Development",
        instructor: "Alex Thompson",
        certificate: "Will be issued upon completion",
      },
      {
        id: 2,
        name: "Liam Johnson",
        email: "liam.j@email.com",
        contact: "+1 (555) 222-3333",
        progress: 100,
        status: "Completed",
        attendance: 98,
        startDate: "Jan 10, 2026",
        course: "Advanced React Development",
        instructor: "Alex Thompson",
        certificate: "Issued",
      },
      {
        id: 3,
        name: "Olivia Brown",
        email: "olivia.b@email.com",
        contact: "+1 (555) 333-4444",
        progress: 75,
        status: "Enrolled",
        attendance: 88,
        startDate: "Jan 10, 2026",
        course: "Advanced React Development",
        instructor: "Alex Thompson",
        certificate: "Pending",
      },
      {
        id: 4,
        name: "Noah Davis",
        email: "noah.d@email.com",
        contact: "+1 (555) 444-5555",
        progress: 20,
        status: "Dropped",
        attendance: 40,
        startDate: "Jan 10, 2026",
        course: "Advanced React Development",
        instructor: "Alex Thompson",
        certificate: "Not eligible",
      },
    ],
  },
  {
    id: 2,
    name: "Leadership & Management",
    category: "Soft Skills",
    duration: "4 weeks",
    instructor: "Sarah Johnson",
    enrolled: 15,
    completed: 15,
    revenue: "$23K",
    progress: 100,
    status: "Completed",
    participants: [
      {
        id: 5,
        name: "Sophia Miller",
        email: "sophia.m@email.com",
        contact: "+1 (555) 555-6666",
        progress: 100,
        status: "Completed",
        attendance: 97,
        startDate: "Feb 5, 2026",
        course: "Leadership & Management",
        instructor: "Sarah Johnson",
        certificate: "Issued",
      },
      {
        id: 6,
        name: "James Garcia",
        email: "james.g@email.com",
        contact: "+1 (555) 666-7777",
        progress: 100,
        status: "Completed",
        attendance: 96,
        startDate: "Feb 5, 2026",
        course: "Leadership & Management",
        instructor: "Sarah Johnson",
        certificate: "Issued",
      },
    ],
  },
  {
    id: 3,
    name: "Cloud Architecture (AWS)",
    category: "Technical",
    duration: "6 weeks",
    instructor: "James Wilson",
    enrolled: 20,
    completed: 12,
    revenue: "$38K",
    progress: 60,
    status: "Active",
    participants: [
      {
        id: 7,
        name: "Isabella Taylor",
        email: "isabella.t@email.com",
        contact: "+1 (555) 777-8888",
        progress: 65,
        status: "Enrolled",
        attendance: 82,
        startDate: "Mar 1, 2026",
        course: "Cloud Architecture (AWS)",
        instructor: "James Wilson",
        certificate: "Pending",
      },
      {
        id: 8,
        name: "Mason Anderson",
        email: "mason.a@email.com",
        contact: "+1 (555) 888-9999",
        progress: 100,
        status: "Completed",
        attendance: 94,
        startDate: "Mar 1, 2026",
        course: "Cloud Architecture (AWS)",
        instructor: "James Wilson",
        certificate: "Issued",
      },
    ],
  },
  {
    id: 4,
    name: "Agile Project Management",
    category: "Management",
    duration: "3 weeks",
    instructor: "Emily Chen",
    enrolled: 18,
    completed: 14,
    revenue: "$27K",
    progress: 78,
    status: "Pending",
    participants: [
      {
        id: 9,
        name: "Ava Thomas",
        email: "ava.t@email.com",
        contact: "+1 (555) 999-1010",
        progress: 78,
        status: "Enrolled",
        attendance: 90,
        startDate: "Apr 10, 2026",
        course: "Agile Project Management",
        instructor: "Emily Chen",
        certificate: "Pending",
      },
    ],
  },
  {
    id: 5,
    name: "UI/UX Design Principles",
    category: "Design",
    duration: "5 weeks",
    instructor: "Maria Garcia",
    enrolled: 22,
    completed: 8,
    revenue: "$33K",
    progress: 36,
    status: "Cancelled",
    participants: [
      {
        id: 10,
        name: "Ethan Clark",
        email: "ethan.c@email.com",
        contact: "+1 (555) 101-2020",
        progress: 36,
        status: "Enrolled",
        attendance: 60,
        startDate: "May 1, 2026",
        course: "UI/UX Design Principles",
        instructor: "Maria Garcia",
        certificate: "Pending",
      },
    ],
  },
];