export const trainingStats = [
  {
    id: 1,
    title: "Revenue Through Training",
    value: "$168.5K",
    subText: "+15% YoY",
    icon: "revenue",
  },
  {
    id: 2,
    title: "Total Programs",
    value: "15",
    subText: "Programs",
    icon: "book",
  },
  {
    id: 3,
    title: "Total Enrolled",
    value: "124",
    subText: "Students",
    icon: "users",
  },
  {
    id: 4,
    title: "Completion Rate",
    value: "87%",
    subText: "Average",
    icon: "trend",
  },
  {
    id: 5,
    title: "Certifications Issued",
    value: "156",
    subText: "YTD",
    icon: "award",
  },
];

export const enrollmentData = [
  { month: "Jan", enrollments: 45 },
  { month: "Feb", enrollments: 52 },
  { month: "Mar", enrollments: 48 },
  { month: "Apr", enrollments: 61 },
  { month: "May", enrollments: 55 },
  { month: "Jun", enrollments: 68 },
];

export const trainingPrograms = [
  {
    id: 1,
    name: "Advanced React Development",
    category: "Technical",
    duration: "8 weeks",
    instructor: "Alex Thompson",
    enrolled: 24,
    completed: 18,
    revenue: "$48K",
    progress: 75,
    status: "Active",
  },
  {
    id: 2,
    name: "Leadership & Management",
    category: "Soft Skills",
    duration: "4 weeks",
    instructor: "Sarah Johnson",
    enrolled: 15,
    completed: 15,
    revenue: "$23K",
    progress: 100,
    status: "Completed",
  },
  {
    id: 3,
    name: "Cloud Architecture (AWS)",
    category: "Technical",
    duration: "6 weeks",
    instructor: "James Wilson",
    enrolled: 20,
    completed: 12,
    revenue: "$38K",
    progress: 60,
    status: "Active",
  },
  {
    id: 4,
    name: "Agile Project Management",
    category: "Management",
    duration: "3 weeks",
    instructor: "Emily Chen",
    enrolled: 18,
    completed: 14,
    revenue: "$27K",
    progress: 78,
    status: "Pending",
  },
  {
    id: 5,
    name: "UI/UX Design Principles",
    category: "Design",
    duration: "5 weeks",
    instructor: "Maria Garcia",
    enrolled: 22,
    completed: 8,
    revenue: "$33K",
    progress: 36,
    status: "Cancelled",
  },
];